# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='productocategoria', to='Catalogos.categoria'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cultivos',
        ),
        migrations.AddField(
            model_name='producto',
            name='cultivos',
            field=models.ManyToManyField(blank=True, related_name='productocultivo', to='Catalogos.Cultivo'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, related_name='productosubcategoria', to='Catalogos.subcategoria'),
        ),
    ]
