# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0002_auto_20171006_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to=b''),
        ),
    ]
