# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 21:18
from __future__ import unicode_literals

import Catalogos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0003_auto_20171006_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='id_catgoria',
            field=models.IntegerField(default=1, verbose_name=Catalogos.models.categoria),
            preserve_default=False,
        ),
    ]
