# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('nombres', models.CharField(blank=True, max_length=800, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=300, null=True)),
                ('localidad', models.CharField(blank=True, max_length=300, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=5000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContactanosCreate', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactanosModified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('filename', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quienessomos', models.CharField(blank=True, max_length=200)),
                ('productos', models.CharField(blank=True, max_length=200)),
                ('pronutiva', models.CharField(blank=True, max_length=200)),
                ('dondeestamos', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('copyright', models.CharField(blank=True, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('textomensaje', models.CharField(blank=True, max_length=5000)),
                ('titulo', models.CharField(blank=True, max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pronutiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('textomensaje', models.CharField(blank=True, max_length=5000)),
                ('image_titulo', models.CharField(blank=True, max_length=500)),
                ('texto_contenido', models.CharField(blank=True, max_length=5000)),
                ('titulo', models.CharField(blank=True, max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuienesSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('textomensaje', models.CharField(blank=True, max_length=2000)),
                ('nosotros', models.CharField(blank=True, max_length=500000)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuienesSomos_acordeon_historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('textomensaje', models.CharField(blank=True, max_length=5000)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuienesSomos_acordeon_mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_entrega', models.CharField(blank=True, max_length=500)),
                ('image_disciplina', models.CharField(blank=True, max_length=500)),
                ('image_responsables', models.CharField(blank=True, max_length=500)),
                ('mision', models.CharField(blank=True, max_length=5000)),
                ('image_clientes', models.CharField(blank=True, max_length=500)),
                ('image_comunidad', models.CharField(blank=True, max_length=500)),
                ('image_empleados', models.CharField(blank=True, max_length=500)),
                ('image_accionistas', models.CharField(blank=True, max_length=500)),
                ('vision', models.CharField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuienesSomos_acordeon_valores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_focalizados', models.CharField(blank=True, max_length=500)),
                ('image_orientados', models.CharField(blank=True, max_length=500)),
                ('image_responsables', models.CharField(blank=True, max_length=500)),
                ('image_respetuosos', models.CharField(blank=True, max_length=500)),
                ('image_comprometidos', models.CharField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion_azul_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('textomensaje', models.CharField(blank=True, max_length=2000)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion_contacto_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('textomensaje', models.CharField(blank=True, max_length=2000)),
                ('mensaje_boton', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion_distribuidor_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('textomensaje', models.CharField(blank=True, max_length=2000)),
                ('mensaje_boton', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion_video_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('textomensaje', models.CharField(blank=True, max_length=2000)),
                ('mensaje_boton', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
