# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='mensaje_boton',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
