# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0002_contacto_mensaje_boton'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='tiutlo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
