# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0003_quienessomos_tiutlo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quienessomos',
            old_name='tiutlo',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='quienessomos_acordeon_mision',
            name='tiutlo_mision',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quienessomos_acordeon_mision',
            name='tiutlo_vision',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
