# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0004_auto_20171005_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuienesSomos_acordeon_mision_imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuienesSomos_acordeon_vision_imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(verbose_name='auth.User')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='auth.User')),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_mision',
            name='image_accionistas',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_mision',
            name='image_clientes',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_mision',
            name='image_comunidad',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_mision',
            name='image_disciplina',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_mision',
            name='image_empleados',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_mision',
            name='image_entrega',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_mision',
            name='image_responsables',
        ),
    ]
