# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManager', '0005_auto_20171005_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quienessomos_acordeon_valores',
            old_name='image_comprometidos',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_valores',
            name='image_focalizados',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_valores',
            name='image_orientados',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_valores',
            name='image_respetuosos',
        ),
        migrations.RemoveField(
            model_name='quienessomos_acordeon_valores',
            name='image_responsables',
        ),
    ]
